on:
  push:
    tags: 'v*'
name: Publish Extension

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Parse version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: cachix/install-nix-action@v16
      - run: |
          npm ci
          ./compile_sqls.fish
          npx vsce package --out sqlnotebook-${{ env.RELEASE_VERSION }}.vsix
        shell: nix develop -c bash {0}
      - name: Upload vsix as artifact
        uses: actions/upload-artifact@v1
        with:
          name: sqlnotebook-${{ env.RELEASE_VERSION }}.vsix
          path: sqlnotebook-${{ env.RELEASE_VERSION }}.vsix
      - name: Publish Extension to Microsoft Marketplace
        run: npx vsce publish --packagePath ./sqlnotebook-${{ env.RELEASE_VERSION }}.vsix
        shell: nix develop -c bash {0}
        env:
          VSCE_PAT: ${{ secrets.VSCE_CREDENTIALS }}
      - name: Publish to OpenVSX
        run: npx ovsx publish ./sqlnotebook-${{ env.RELEASE_VERSION }}.vsix -p ${{ secrets.OPEN_VSX_CREDENTIALS }}
        shell: nix develop -c bash {0}
