name: Publish Extension
on:
  push:
    tags: 'v*'

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Parse version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: nix build
      - name: Prepare to upload
        run: cp ./result/* sqlnotebook-${{ env.RELEASE_VERSION }}.vsix
      - run: touch sqlnotebook-${{ env.RELEASE_VERSION }}.vsix
      - name: Upload vsix as artifact
        uses: actions/upload-artifact@v1
        with:
          name: sqlnotebook-${{ env.RELEASE_VERSION }}.vsix
          path: sqlnotebook-${{ env.RELEASE_VERSION }}.vsix
      - name: Publish Extension to Microsoft Marketplace
        run: npx vsce publish --packagePath ./sqlnotebook-${{ env.RELEASE_VERSION }}.vsix
        env:
          VSCE_PAT: ${{ secrets.VSCE_CREDENTIALS }}
      - name: Publish to OpenVSX
        run: npx ovsx publish ./sqlnotebook-${{ env.RELEASE_VERSION }}.vsix -p ${{ secrets.OPEN_VSX_CREDENTIALS }}
